#
# https://docs.travis-ci.com/user/reference/trusty/#Image-differences-from-Precise
#

dist: trusty
sudo: required

language: javascript

addons:
  firefox: "latest"

before_install:
  - "uname -a"
  - "gcc --version"
  - "lsb_release -a"
  - "npm version"
  - "nvm install v6.11.2"
  - "nvm use v6.11.2"
  - "npm version"
  - "npm install -g npm@latest"
  - "npm version"
  - "#disabledForNow# phantomjs --version"
  - "sudo apt-get update -q"
  - "sudo apt-get install build-essential chrpath libssl-dev libxft-dev -y"
  - "sudo apt-get install libfreetype6 libfreetype6-dev -y"
  - "sudo apt-get install libfontconfig1 libfontconfig1-dev -y"
  - "pushd ~"
  - "echo $PATH"
  - "#disabledForNow# export PHANTOM_JS=\"phantomjs-2.1.1-linux-x86_64\""
  - "#disabledForNow# wget https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOM_JS}.tar.bz2"
  - "#disabledForNow# sudo tar xvjf ${PHANTOM_JS}.tar.bz2"
  - "#disabledForNow# which phantomjs"
  - "#disabledForNow# ls -R /usr/local/phantomjs/"
  - "#disabledForNow# sudo mv /usr/local/phantomjs /usr/local/phantomjs_old"
  - "#disabledForNow# sudo mv ${PHANTOM_JS} /usr/local/phantomjs"
  - "#disabledForNow# sudo ln -sf /usr/local/phantomjs/bin/phantomjs /usr/local/bin"
  - "#disabledForNow# sudo ln -sf /usr/local/phantomjs/bin/phantomjs /usr/local/phantomjs/phantomjs"
  - "#disabledForNow# /usr/local/phantomjs/phantomjs --version"
  - "#disabledForNow# /usr/local/bin/phantomjs --version"
  - "#disabledForNow# phantomjs --version"
  - "#disabledForNow# which phantomjs"
  - "wget https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz"
  - "tar -xvzf geckodriver-v0.19.0-linux64.tar.gz"
  - "chmod +x geckodriver"
  - "sudo mv geckodriver /usr/local/bin/"
  - "firefox -v"
  - "popd"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

# command to install dependencies
install:
  - "rm -rf node_modules/"
  - "./install.sh"
  - "ls -lhS dist/"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  - "sudo pip install jsonpath-rw"

before_script:
  - "export DISPLAY=:99.0"
  - "ls -lhS dist/"
  - "USE_LOG_FETCH=1 npm run startbeta &"
  - "# NODE_PATH=./lib/monarch USE_BUNDLE=1 USE_LOG_FETCH=1 node ./lib/monarch/web/webapp_launcher.js beta &"
  - "sleep 20"

after_success:
  - "cat ./webdriver.log"
  - "cat ../../start-server.log"

after_failure:
  - "cat ./webdriver.log"
  - "cat ../../start-server.log"

# command to run tests
script:
  - "ps auwx|grep webapp_launcher.js"
  - "USE_LOG_FETCH=1 make test"
  - "pushd tests/behave"
  - "# Testing with Firefox"
  - "firefox -v"
  - "TARGET=http://localhost:8080 behave --no-capture"
  - "# Testing with PhantomJS"
  - "# phantomjs -v"
  - "# TARGET=http://localhost:8080 BROWSER=phantomjs behave --no-capture"
  - "popd"

# whitelist
branches:
  only:
    - master
    - production
    - stage

notifications:
  email:
    - keitda@ohsu.edu
    - kshefchek@gmail.com
